require 'config.plugins.statusline'
require 'config.plugins.lsp'
require 'config.plugins.telescope'
require 'config.plugins.treesitter'
require 'config.plugins.completion'
require 'config.plugins.autopairs'
require 'config.plugins.comments'
require 'config.plugins.git'
